# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_connection_form.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_OpenConnectionForm(object):
    def setupUi(self, OpenConnectionForm):
        OpenConnectionForm.setObjectName("OpenConnectionForm")
        OpenConnectionForm.resize(487, 222)
        self.verticalLayout = QtGui.QVBoxLayout(OpenConnectionForm)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(OpenConnectionForm)
        self.label_4.setMinimumSize(QtCore.QSize(60, 60))
        self.label_4.setMaximumSize(QtCore.QSize(60, 60))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/res/p4_icon.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(OpenConnectionForm)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(12, -1, 12, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.user_browse_btn = QtGui.QPushButton(OpenConnectionForm)
        self.user_browse_btn.setObjectName("user_browse_btn")
        self.gridLayout.addWidget(self.user_browse_btn, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(OpenConnectionForm)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(OpenConnectionForm)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.workspace_browse_btn = QtGui.QPushButton(OpenConnectionForm)
        self.workspace_browse_btn.setObjectName("workspace_browse_btn")
        self.gridLayout.addWidget(self.workspace_browse_btn, 2, 3, 1, 1)
        self.workspace_edit = QtGui.QLineEdit(OpenConnectionForm)
        self.workspace_edit.setObjectName("workspace_edit")
        self.gridLayout.addWidget(self.workspace_edit, 2, 2, 1, 1)
        self.label = QtGui.QLabel(OpenConnectionForm)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.user_edit = QtGui.QLineEdit(OpenConnectionForm)
        self.user_edit.setObjectName("user_edit")
        self.gridLayout.addWidget(self.user_edit, 1, 2, 1, 1)
        self.server_edit = QtGui.QLineEdit(OpenConnectionForm)
        self.server_edit.setReadOnly(True)
        self.server_edit.setObjectName("server_edit")
        self.gridLayout.addWidget(self.server_edit, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 81, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.break_line = QtGui.QFrame(OpenConnectionForm)
        self.break_line.setFrameShape(QtGui.QFrame.HLine)
        self.break_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.break_line.setObjectName("break_line")
        self.verticalLayout.addWidget(self.break_line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(12, 8, 12, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cancel_btn = QtGui.QPushButton(OpenConnectionForm)
        self.cancel_btn.setMinimumSize(QtCore.QSize(90, 0))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_3.addWidget(self.cancel_btn)
        self.ok_btn = QtGui.QPushButton(OpenConnectionForm)
        self.ok_btn.setMinimumSize(QtCore.QSize(90, 0))
        self.ok_btn.setDefault(True)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_3.addWidget(self.ok_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(OpenConnectionForm)
        QtCore.QMetaObject.connectSlotsByName(OpenConnectionForm)
        OpenConnectionForm.setTabOrder(self.server_edit, self.user_edit)
        OpenConnectionForm.setTabOrder(self.user_edit, self.user_browse_btn)
        OpenConnectionForm.setTabOrder(self.user_browse_btn, self.workspace_edit)
        OpenConnectionForm.setTabOrder(self.workspace_edit, self.workspace_browse_btn)
        OpenConnectionForm.setTabOrder(self.workspace_browse_btn, self.cancel_btn)
        OpenConnectionForm.setTabOrder(self.cancel_btn, self.ok_btn)

    def retranslateUi(self, OpenConnectionForm):
        OpenConnectionForm.setWindowTitle(QtGui.QApplication.translate("OpenConnectionForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OpenConnectionForm", "Enter your connection settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.user_browse_btn.setText(QtGui.QApplication.translate("OpenConnectionForm", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OpenConnectionForm", "Workspace:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OpenConnectionForm", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.workspace_browse_btn.setText(QtGui.QApplication.translate("OpenConnectionForm", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OpenConnectionForm", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("OpenConnectionForm", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_btn.setText(QtGui.QApplication.translate("OpenConnectionForm", "Ok", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
